{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.5.1.aar",
          "url": "navigation-compose-2.5.1.aar",
          "size": 1095739,
          "sha512": "e8d604274d879cde4a06c0b3dffe46bcc1ce4350f04a4419158002a04905f3092bb3c3b481d8a7fef211589480f9eec814f3941bf1fcb4f174bb1cb62f78ca09",
          "sha256": "68cea6d18d1ef1b7cbfcf636e4b783d76c857eb3b0746396aeb0e0d678c90b30",
          "sha1": "4164c14c3f4d585ac5d2e3e5b614d1c8e785b05c",
          "md5": "6aa6155e69f4c4d40f598e41a22a4cb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.5.1.aar",
          "url": "navigation-compose-2.5.1.aar",
          "size": 1095739,
          "sha512": "e8d604274d879cde4a06c0b3dffe46bcc1ce4350f04a4419158002a04905f3092bb3c3b481d8a7fef211589480f9eec814f3941bf1fcb4f174bb1cb62f78ca09",
          "sha256": "68cea6d18d1ef1b7cbfcf636e4b783d76c857eb3b0746396aeb0e0d678c90b30",
          "sha1": "4164c14c3f4d585ac5d2e3e5b614d1c8e785b05c",
          "md5": "6aa6155e69f4c4d40f598e41a22a4cb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-2.5.1-sources.jar",
          "url": "navigation-compose-2.5.1-sources.jar",
          "size": 10998,
          "sha512": "74fc7e04fe39d90cfc265654cc0b55b20f1ab3d80ab4ad81d58729cf937188a1cd9dc3e8bb53dc054ec61333406354acb7e3d42e4281e2c082e57a37cb749f06",
          "sha256": "f91b4a3ccd95974562d6b56004310e4d32ce2f107f302e815a73ea41da4601d6",
          "sha1": "8b1dd15fa0586e9f0850d9a3e3ece7bec443a75a",
          "md5": "8db21b74d722c7d7e7c866b240daa1cf"
        }
      ]
    }
  ]
}