{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.0.aar",
          "url": "camera-lifecycle-1.3.0.aar",
          "size": 22530,
          "sha512": "84fad7d2dafedfaed75ba4aa4c7c97cc5489abc0cde1deb8f56b68c7b2281317b7ee6939389dbfd9a6d85c237fa756e3fb6a363b85a38ab7ed3a13845e388712",
          "sha256": "d66f0e2bf9ab1058fed06685c2eaec5357f7940d405a0d38f8a1b2d471208202",
          "sha1": "d8734021b945fea1faf2c87d262ef66eb02ff9c8",
          "md5": "313e7ea6cdbc870d978b54c9ca52e081"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.0.aar",
          "url": "camera-lifecycle-1.3.0.aar",
          "size": 22530,
          "sha512": "84fad7d2dafedfaed75ba4aa4c7c97cc5489abc0cde1deb8f56b68c7b2281317b7ee6939389dbfd9a6d85c237fa756e3fb6a363b85a38ab7ed3a13845e388712",
          "sha256": "d66f0e2bf9ab1058fed06685c2eaec5357f7940d405a0d38f8a1b2d471208202",
          "sha1": "d8734021b945fea1faf2c87d262ef66eb02ff9c8",
          "md5": "313e7ea6cdbc870d978b54c9ca52e081"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.0-sources.jar",
          "url": "camera-lifecycle-1.3.0-sources.jar",
          "size": 19479,
          "sha512": "99b47bbc7e73be98edc3bf398ba7f6258c388699aa5643aefe24d95275e8428da6ae33a59cd7c387cebcfe5a78aef6d3cc45495421cd19a08fc4aec52c6f67ed",
          "sha256": "d9b8215f54dbb15ed6fffcdfe96cc436fc3897e77c73a2ff986210ba3ebfbd32",
          "sha1": "fadc8569bbf7f44a7a5425643064db16fdd0c131",
          "md5": "4fcb231a866441ec8bbd6253fe25545c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-core",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.0-versionMetadata.json",
          "url": "camera-lifecycle-1.3.0-versionMetadata.json",
          "size": 1358,
          "sha512": "fc6308cedc83dac01c2f6b8a92842220fd3e101dd76c9eee882b2ccbd548231ee1b54cec52d6c9d2f2e5738e4ea3a910621901cd813b2de43583bb3632b9a4ed",
          "sha256": "c5e23298f455b8a300eeada14f2bcc6b17b05728bc5921da16d9271eb2d92385",
          "sha1": "56bf15d1635c5e0f4755d09ec2163c9d8288e56f",
          "md5": "5961ecfeac455ca690ed426915a72bef"
        }
      ]
    }
  ]
}