{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.5.4-multiplatform-sources.jar",
          "url": "material-icons-extended-1.5.4-multiplatform-sources.jar",
          "size": 571,
          "sha512": "a1ac2b15ae34b1e94017abdec50b84ec1851f49726ab4c451fdf51118f46dd6bebdd6cb53e1c77663d3d5be744331d3100975a06c4973ab3975bfd943c338052",
          "sha256": "bee5e4efffff62f2593aa2b401c17ae4be6b09e02f0254979022c579e6acabe1",
          "sha1": "b20d8d18b4ec5a759d42c5a1dc4b167a19b2c4ed",
          "md5": "bff0beace22d5f7128c824fbf82def0c"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-metadata-1.5.4.jar",
          "url": "material-icons-extended-1.5.4.jar",
          "size": 691,
          "sha512": "423d9ccb58f492f788981b6f6e810f515c31aff32842a91163c9da2c9e43a570af6e919cc52a1229a09f08f59412925fd836280242092661cd21a1940444c7ab",
          "sha256": "d2e958b95adf384d4c9e4a1f6ca1c22360ac596f92a83bd917be5ea912eeba21",
          "sha1": "49a0810332e11e446be57cbf06dac54390538820",
          "md5": "dfc7de03a224816f586cfcaa12977619"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-kotlin-1.5.4-sources.jar",
          "url": "material-icons-extended-1.5.4-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-extended-android/1.5.4/material-icons-extended-android-1.5.4.module",
        "group": "androidx.compose.material",
        "module": "material-icons-extended-android",
        "version": "1.5.4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-extended-android/1.5.4/material-icons-extended-android-1.5.4.module",
        "group": "androidx.compose.material",
        "module": "material-icons-extended-android",
        "version": "1.5.4"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-extended-android/1.5.4/material-icons-extended-android-1.5.4.module",
        "group": "androidx.compose.material",
        "module": "material-icons-extended-android",
        "version": "1.5.4"
      }
    }
  ]
}