{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "1.9.0-1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.9.0-1.0.12.jar",
          "url": "symbol-processing-api-1.9.0-1.0.12.jar",
          "size": 119453,
          "sha512": "1ab5577424e36eb6aebf06be1afa363ef7f8a7f4d3ed330e1e24180eb712b1058b38edd2d958b219402d4f8b24b5ab7a7f079a28f8189c49e6698d0e0fd91ff6",
          "sha256": "804b0465abb504db483fa4e5a58b154386992c6ec882e7d1d7524791a489b6b5",
          "sha1": "76d0c8d0e7e65707dc4a1963952b61660248e96e",
          "md5": "5297185d4b08f9b992ff6d8b693cef47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.9.0-1.0.12.jar",
          "url": "symbol-processing-api-1.9.0-1.0.12.jar",
          "size": 119453,
          "sha512": "1ab5577424e36eb6aebf06be1afa363ef7f8a7f4d3ed330e1e24180eb712b1058b38edd2d958b219402d4f8b24b5ab7a7f079a28f8189c49e6698d0e0fd91ff6",
          "sha256": "804b0465abb504db483fa4e5a58b154386992c6ec882e7d1d7524791a489b6b5",
          "sha1": "76d0c8d0e7e65707dc4a1963952b61660248e96e",
          "md5": "5297185d4b08f9b992ff6d8b693cef47"
        }
      ]
    }
  ]
}
