{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.2.0.jar",
          "url": "builder-8.2.0.jar",
          "size": 12178510,
          "sha512": "03060c9199fe585286d080b7ad72a98950cf43f050bad7c732fddd17c5798019ea7c395acb189a1d86ce319d5baadc3b6420a4748b589094b3d58a1015515e9e",
          "sha256": "03ee1ec9cd9836c5e29a6e94402cd276c591bec1cce66523141fd90deb7fe809",
          "sha1": "1ffd583497203457bdedf4c4f771a5f85b36d1e3",
          "md5": "32a8af1477ac4e385be0e819cb7a0db7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.2.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.2.0.jar",
          "url": "builder-8.2.0.jar",
          "size": 12178510,
          "sha512": "03060c9199fe585286d080b7ad72a98950cf43f050bad7c732fddd17c5798019ea7c395acb189a1d86ce319d5baadc3b6420a4748b589094b3d58a1015515e9e",
          "sha256": "03ee1ec9cd9836c5e29a6e94402cd276c591bec1cce66523141fd90deb7fe809",
          "sha1": "1ffd583497203457bdedf4c4f771a5f85b36d1e3",
          "md5": "32a8af1477ac4e385be0e819cb7a0db7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.2.0-javadoc.jar",
          "url": "builder-8.2.0-javadoc.jar",
          "size": 400792,
          "sha512": "22404df1497622d2cfb396fc751ca35759a1b70e0a55ff55f2ab9c7165938665a28fc2c5200151892422a6c44c9b21219d338dc388d5561d42b84bcae804c2f1",
          "sha256": "57ee5d2272cec5d144d55188f1ca5245ab087be5e78bfa0802bdaa1369f05324",
          "sha1": "80682215af2c5b9c7815a163e2d675ff6c73d9f8",
          "md5": "7779fb0ab7c22f33ad1682c157497fc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.2.0-sources.jar",
          "url": "builder-8.2.0-sources.jar",
          "size": 281987,
          "sha512": "52ac272eb7a3a0d1bbdbfa8bc6e4251dc27ba8c3e62ea5c3ff545b7a9c4facc01b71a9699bdc74d487b1f8ec5613686772f035946b75bb238783c64caba093c7",
          "sha256": "ad5d427b766d6bc09f9f8b7254d24453a109dc3fe1b120d838aa646e46814216",
          "sha1": "58fe4f45d3b29fb5e1c178bc4ff8d991723bd52b",
          "md5": "cd59e8bfd6f1bc3977c6c8bacac6fab7"
        }
      ]
    }
  ]
}
