{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.5.1.aar",
          "url": "navigation-runtime-2.5.1.aar",
          "size": 121098,
          "sha512": "e30c266347700b668bc09a31ec3f6a4279353ba979c3c17f2c9c1fb62331cae2f20c201fdc79fe656303f429209a06be01cfa2315040e15c77e7334cee4c84de",
          "sha256": "3e8171b96e3edf0b3c4796d280ee94bf3ebd64aeec07123b158c7964cb945c1c",
          "sha1": "80162a450d0e1a35134740a91b07e62ccc77926c",
          "md5": "3dc1269239af72092dc0cfad2b82d959"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.5.1.aar",
          "url": "navigation-runtime-2.5.1.aar",
          "size": 121098,
          "sha512": "e30c266347700b668bc09a31ec3f6a4279353ba979c3c17f2c9c1fb62331cae2f20c201fdc79fe656303f429209a06be01cfa2315040e15c77e7334cee4c84de",
          "sha256": "3e8171b96e3edf0b3c4796d280ee94bf3ebd64aeec07123b158c7964cb945c1c",
          "sha1": "80162a450d0e1a35134740a91b07e62ccc77926c",
          "md5": "3dc1269239af72092dc0cfad2b82d959"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.5.1-sources.jar",
          "url": "navigation-runtime-2.5.1-sources.jar",
          "size": 46530,
          "sha512": "e32bf9b29cb38ecc24b23712689224cc7179293cde095ac8748b7e2c02786280a33b9dc71f26add95838e84d7cf5e14e6889ac1565116a506ad8e339df311089",
          "sha256": "ac066753327766f1a151ab3e8f7b9136e5c006a551398b256eff16c660439047",
          "sha1": "fbf2621a7c1cb8f21baedebccc884425e8e2e996",
          "md5": "ef4dd50dcc1d35271a7fc75915dc965f"
        }
      ]
    }
  ]
}