{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.1.aar",
          "url": "navigation-runtime-ktx-2.5.1.aar",
          "size": 1770,
          "sha512": "4172f3368aaf844b9bd82ee7cc85761b012022380a807b17370e92c1a1a2a9e4035f8662748a1b0f4a300136514c8ac97bbf1c4b594373d2f29ba223225553a7",
          "sha256": "e71d6c9fa81e244acd55df7e3e16ac4ea15aecafd30e80e645d72f5feff93591",
          "sha1": "1d260f80ecb2880288f018d87ce1fbb3018da98c",
          "md5": "a4c0d36c0d90322cabfaecd9dae32c0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.1.aar",
          "url": "navigation-runtime-ktx-2.5.1.aar",
          "size": 1770,
          "sha512": "4172f3368aaf844b9bd82ee7cc85761b012022380a807b17370e92c1a1a2a9e4035f8662748a1b0f4a300136514c8ac97bbf1c4b594373d2f29ba223225553a7",
          "sha256": "e71d6c9fa81e244acd55df7e3e16ac4ea15aecafd30e80e645d72f5feff93591",
          "sha1": "1d260f80ecb2880288f018d87ce1fbb3018da98c",
          "md5": "a4c0d36c0d90322cabfaecd9dae32c0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.1-sources.jar",
          "url": "navigation-runtime-ktx-2.5.1-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}