{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.1.aar",
          "url": "navigation-common-ktx-2.5.1.aar",
          "size": 1771,
          "sha512": "17a73cdad3bdd482ac895823f1c9faf54b975c274e4bc83217cdf6f5499c834bc8c6af1e063b7dd513cc6c858732b84e1b3c1233e74c832c778214b9d2205dfd",
          "sha256": "f746fe4cb8ee2370d2be7f503233dfd1948f5fedfe7be7c6c50c373aefdf1b51",
          "sha1": "ee193bbbddd39bf040ed7fb1f0d4a92c4a3e38b1",
          "md5": "e824c59544c8623e94cb519a19431253"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.1.aar",
          "url": "navigation-common-ktx-2.5.1.aar",
          "size": 1771,
          "sha512": "17a73cdad3bdd482ac895823f1c9faf54b975c274e4bc83217cdf6f5499c834bc8c6af1e063b7dd513cc6c858732b84e1b3c1233e74c832c778214b9d2205dfd",
          "sha256": "f746fe4cb8ee2370d2be7f503233dfd1948f5fedfe7be7c6c50c373aefdf1b51",
          "sha1": "ee193bbbddd39bf040ed7fb1f0d4a92c4a3e38b1",
          "md5": "e824c59544c8623e94cb519a19431253"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.5.1-sources.jar",
          "url": "navigation-common-ktx-2.5.1-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}