{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.5"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.5.jar",
          "url": "compiler-1.5.5.jar",
          "size": 1106409,
          "sha512": "1f18a5045b1ff6dc3aa85f38f7e7181d0c70442d3e88a37051be58f05c31d62a9b3fa4daf28d2300ab1034446b7e7e06c082d45e292ec14bd843abba023223ee",
          "sha256": "423fbbc35a14eff733c08e768a3f1cf1b53c8b37dc18c6ccae4f4ab8d24d0082",
          "sha1": "d1f09403ec743868cf309d9cd268f36a2b019604",
          "md5": "df29acc36eb6409c230b7af6ae5c03ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.5"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.5.jar",
          "url": "compiler-1.5.5.jar",
          "size": 1106409,
          "sha512": "1f18a5045b1ff6dc3aa85f38f7e7181d0c70442d3e88a37051be58f05c31d62a9b3fa4daf28d2300ab1034446b7e7e06c082d45e292ec14bd843abba023223ee",
          "sha256": "423fbbc35a14eff733c08e768a3f1cf1b53c8b37dc18c6ccae4f4ab8d24d0082",
          "sha1": "d1f09403ec743868cf309d9cd268f36a2b019604",
          "md5": "df29acc36eb6409c230b7af6ae5c03ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.5"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.5-sources.jar",
          "url": "compiler-1.5.5-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}