{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.8.1.aar",
          "url": "activity-compose-1.8.1.aar",
          "size": 1135179,
          "sha512": "fa78ac3db3f35fe1ab8cfa939ae84653a5d884dd121f9fe0b13b275c497a77da07a83eb6ba1c52a5a58702d7100f3bf157118514be525b133ef09df61bb9ac1e",
          "sha256": "73d44cf026ba5f685829c2085f7a08fb012d7fc6b5757413535731728b98d71b",
          "sha1": "bc759b14641fca1f2a6aae59f824d867d3e798f8",
          "md5": "92c1993339cd7d4985d5267232516722"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.8.1.aar",
          "url": "activity-compose-1.8.1.aar",
          "size": 1135179,
          "sha512": "fa78ac3db3f35fe1ab8cfa939ae84653a5d884dd121f9fe0b13b275c497a77da07a83eb6ba1c52a5a58702d7100f3bf157118514be525b133ef09df61bb9ac1e",
          "sha256": "73d44cf026ba5f685829c2085f7a08fb012d7fc6b5757413535731728b98d71b",
          "sha1": "bc759b14641fca1f2a6aae59f824d867d3e798f8",
          "md5": "92c1993339cd7d4985d5267232516722"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.8.1-sources.jar",
          "url": "activity-compose-1.8.1-sources.jar",
          "size": 10803,
          "sha512": "3b4c39fd06f17bfb80cc7692a02eb216e98e56e91291aafbc56aa2c7478ac9b2dabc2824b3124d0fb816ed28eb099b4081b59a2e1cd62186d0f7839d6635b432",
          "sha256": "358704e10165cacb8140b996e50d4b58edf4618b25e61a2289627dd1b32a1f3b",
          "sha1": "6c5ebff07639f79cfcf9f86a3e08a7c9397748f8",
          "md5": "a9687103cb09ed61bf260a0012782fab"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.8.1-versionMetadata.json",
          "url": "activity-compose-1.8.1-versionMetadata.json",
          "size": 2701,
          "sha512": "5bcbe87abf1523796cbd86aabcb6ad0d668eae24476c50325302ca32b53d6f148578c74693024e6fed23b65db04a2b0a5309d4563c9cfeced17b61ea5cd29f5b",
          "sha256": "729bfa5b3edab37f58d8bf7146c058fa7ed2d43b940fca0e2595316dc304a60e",
          "sha1": "fc1dbba8ce429a7d29725c89b0df0584364b0f9f",
          "md5": "c6437fc952fbb6d4e28056b0859a44b8"
        }
      ]
    }
  ]
}