{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.5.4-multiplatform-sources.jar",
          "url": "foundation-1.5.4-multiplatform-sources.jar",
          "size": 539346,
          "sha512": "f3e1a25212547356cb67a809c414e29b7b6fedd2836792d2307e3e069e5abdd977c503fb36d5eaa97069204d499d42209a7545ff870212b765c320cef76e92ae",
          "sha256": "327acf4dbe52ece9ade45bdeaea1936119f430be5fb1c4fa656e2e2134e68b34",
          "sha1": "cbd2c973e79ebfebde048e541bb21f82ce843b27",
          "md5": "2f421d13e3e2c94ee8565fcc2683944c"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-1.5.4.jar",
          "url": "foundation-1.5.4.jar",
          "size": 699,
          "sha512": "d71b17b5649558d784f82bc0af1217ef1afe49eb196f62b82c0ca90ed28cda663b87221b6064ac38f616f8cb79d5260ef95a3d8303d86ae68213dcea9fd28820",
          "sha256": "84ba53af9fd289476e76b74216d43ee54006cc587c0fdbec51c8cdf717ab5e7f",
          "sha1": "e302b298fec1cf66e48f9df93c34861cd397f348",
          "md5": "3b96fde7a4bd717cf81ed234e17ff2ad"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-kotlin-1.5.4-sources.jar",
          "url": "foundation-1.5.4-sources.jar",
          "size": 489382,
          "sha512": "21eb8992dbabc9ce84c89a3bb514c168681e5cb77ff2bd0eb44ab08de25076a118ce6a1e795b48e22a3d4f942428013ee9b0a373caead184512387bf6649a141",
          "sha256": "6ec83200653a59eb332f8d672bc8e3652a7e3e86cdaa3bd08f1e56a7a56b8461",
          "sha1": "d3a506e19b7d38670d63bc2aa8bf5507f7d41c4c",
          "md5": "475a075ca388994dc1a5bcb52261a70e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.5.4/foundation-android-1.5.4.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.5.4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.5.4/foundation-android-1.5.4.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.5.4"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.5.4/foundation-android-1.5.4.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.5.4"
      }
    }
  ]
}