{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.5.1.aar",
          "url": "navigation-common-2.5.1.aar",
          "size": 155950,
          "sha512": "194c6b7bd88d4cdf10e94cdb42c2d4be202a8def562bf7e0e939ea59d83f33026165331cef9bd5db3eb38a0c015f857a9cf88b51b8c1064ec7921823995a2895",
          "sha256": "6960a8e09e0b2fcc5f7f0d1a3299f938faad18ab4656506038e27527d04eb08a",
          "sha1": "75f03f760a3357c0656703a16dc7635b00628660",
          "md5": "d30296688ec3d29dd5c014b4f115da13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.5.1.aar",
          "url": "navigation-common-2.5.1.aar",
          "size": 155950,
          "sha512": "194c6b7bd88d4cdf10e94cdb42c2d4be202a8def562bf7e0e939ea59d83f33026165331cef9bd5db3eb38a0c015f857a9cf88b51b8c1064ec7921823995a2895",
          "sha256": "6960a8e09e0b2fcc5f7f0d1a3299f938faad18ab4656506038e27527d04eb08a",
          "sha1": "75f03f760a3357c0656703a16dc7635b00628660",
          "md5": "d30296688ec3d29dd5c014b4f115da13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.5.1-sources.jar",
          "url": "navigation-common-2.5.1-sources.jar",
          "size": 54874,
          "sha512": "862c0be71f12a6f62a5fd874cd2c996ccdf74813637cdfac24ca479dfab1421f08afa92b04ea1a640908250d203dc85f453a5bf3041644360c90274bfb201600",
          "sha256": "a775c00223af5ca08949d75165877f9b6582e6eb018d1f131bc7288e8de4d1df",
          "sha1": "f1d0bca09bca0aefde801761736f097f6710c803",
          "md5": "bd0a87fcf266ca4f83a361f68fd7b9ed"
        }
      ]
    }
  ]
}